### PR TITLE
Load the ZFS module when not present

### LINKED ISSUE #90: Incorrect error message from zpool command
On FreeBSD, the message zpool prints when trying to create a pool without the zfs module loaded is incorrect. It should just load the module for the user, but it definitely shouldn't require `udevadm trigger`on FreeBSD.

```
root@freebsd12-zol:~ # zpool create tank foo
/dev/zfs and /proc/self/mounts are required.
Try running 'udevadm trigger' and 'mount -t proc proc /proc' as root.
root@freebsd12-zol:~ #
```

### PR DESCRIPTION
**Pull request by ghost**
Use libzfs_load() implementation from FreeBSD to load zfs.ko when not present during libzfs initialization. Make the error messages for this relevant to FreeBSD.
Ifdef out an unused function to check if the module is loaded, which already exists as `modfind(3)` on FreeBSD.

Fixes #90

### CODE REVIEW

File: lib/libzfs/libzfs_util.c [hunk 1]
```diff
@@ -911,16 +925,24 @@ libzfs_envvar_is_set(char *envvar)
 static int
 libzfs_load_module(const char *module)
 {
+#ifdef __FreeBSD__
+
+	if (modfind(module) < 0) {
+		/* Not present in kernel, try loading it. */
+		if (kldload(module) < 0 || modfind(module) < 0) {
+			if (errno != EEXIST)
+				return (-1);
```
Comment (allanjude) [inline lib/libzfs/libzfs_util.c]: shouldn't we return errno here, rather than -1?

Comment (ghost) [reply lib/libzfs/libzfs_util.c]: Thanks for catching that, and it made me think twice about the error messages, too.
